#include "561_Array_Partition_I.h"
#include "728_Self_Dividing_Numbersr.h"
#include "771_Jewels_and_Stones.h"
#include "412_Fizz_Buzz.h"
#include "575_Distribute_Candies.h"
#include "937_Reorder_Log_Files.h"
